import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Recipe Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900`}
      >
        <Providers>
          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              className: "bg-orange-100 text-orange-400 rounded-lg",
              success: {
                className: "bg-orange-100 text-white",
              },
              error: {
                className: "bg-red-100 text-white",
              },
            }}
          />
          <header>
            <Navbar />
          </header>
          <main className="duration-900 mx-auto min-h-dvh w-11/12 max-w-7xl">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
